array
    (
       "Start" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Início",
        "Title_UK" => "Start",
        "Name"     => "Início",
        "Name"     => "Start",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"    => 1,
        "Handler"   => "HandleStart",
       ),
       "Logon" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Efetuar Login",
        "Title_UK" => "Do Login",
        "Name"     => "Login",
        "Name"     => "Login",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"    => 1,
        "Handler"   => "HandleLogon",
       ),
       "Logoff" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Sair do Sistema",
        "Title_UK" => "Logoff from the system",
        "Name"     => "Logoff",
        "Name_UK"  => "Logoff",
        "Public"   => 1,
        "Person"   => 1,
        "Admin"   => 1,
        "Handler"   => "HandleLogoff",
        "NoHeads"   => 1,
       ),
       "NewPassword" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Trocar sua Senha",
        "Title_UK" => "Change Your Password",
        "Name"     => "Alterar Senha",
        "Name_UK"  => "Change Password",
        "Public"   => 0,
        "Person"   => 1,
        "Admin"   => 1,
        "Handler"   => "ChangePasswordForm",
       ),
       "Recover" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Recuperar sua Senha",
        "Title_UK" => "Recover Your Password",
        "Name"     => "Recuperar Senha",
        "Name_UK"  => "Recover Password",
        "Public"   => 1,
        "Person"   => 0,
        "Admin"   => 0,
        "Handler"   => "HandleRecover",
       ),
       "MyData" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Atualizar seus Dados Pessoas",
        "Title_UK" => "Update Your Personal Data",
        "Name"     => "Dados Pessoa",
        "Name_UK"  => "Personal Data",
        "Public"   => 0,
        "Person"   => 1,
        "Admin"   => 1,
        "Handler"   => "HandleMyData",
       ),
       "SU" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "AddIDArg"   => 0,
        "Title"    => "Trocar Usuário",
        "Title_UK" => "Become Another User",
        "Name"     => "SU",
        "Name_UK"  => "SU",
        "Public"   => 0,
        "Person"   => 0,
        "Distributor"   => 1,
        "Admin"   => 1,
        "Handler"   => "HandleSU",
       ),
       "UnSU" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "AddIDArg"   => 0,
        "Title"    => "Voltar para Usuário Prévia",
        "Title_UK" => "Return to Previous User",
        "Name"     => "Voltar SU",
        "Name_UK"  => "Undo SU",
        "Public"   => 0,
        "Person"   => 0,
        //"Distributor"   => 0,
        "AccessMethod"   => "UnSUAccess",
        "Admin"   => 0,
        "Handler"   => "HandleUnSU",
       ),
       "Log" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Ver os Logs",
        "Title_UK" => "See the Logs",
        "Name"     => "Logging",
        "Name_UK"  => "Logging",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Handler"   => "HandleLog",
       ),
       "Backup" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Efetuar Backup",
        "Title_UK" => "Perform Backup",
        "Name"     => "Backup",
        "Name_UK"  => "Backup",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Handler"   => "HandleBackup",
        "NoHeads"   => 1,
        "NoInterfaceMenu"   => 1,
       ),
       "Setup" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Editar Setup",
        "Title_UK" => "Edit Setup",
        "Name"     => "Setup",
        "Name_UK"  => "Setup",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Handler"   => "HandleSetup",
       ),
       "Modules" => array
       (
        "Href"     => "",
        "HrefArgs" => "",
        "Title"    => "Permissões e Perfís por Módulo",
        "Title_UK" => "Permissions and Profiles per Module",
        "Name"     => "Módulos",
        "Name_UK"  => "Modules",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Handler"   => "HandleModuleSetup",
       ),
       "Admin" => array
       (
        "Href"     => "",
        "HrefArgs" => "Admin=1",
        "AddIDArg"   => 0,
        "Title"    => "Login como Administrador",
        "Title_UK" => "Become Administrator",
        "Name"     => "Admin",
        "Name_UK"  => "Admin",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "ConditionalAdmin"   => 1,
        "Handler"   => "HandleAdmin",
       ),
       "NoAdmin" => array
       (
        "Href"     => "",
        "HrefArgs" => "Admin=0",
        "AddIDArg"   => 0,
        "Title"    => "Deixar de ser Admin",
        "Title_UK" => "Leave Admin Mode",
        "Name"     => "NoAdmin",
        "Name_UK"  => "NoAdmin",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "ConditionalAdmin"   => 1,
        "Handler"   => "HandleNoAdmin",
       ),
    );
