array
(
   "StudentMarks" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=StudentMarks&Student=#ClassStudent",
      "Name"    => "Notas",
      "Title"     => "Gerenciar Avaliações do Aluno",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Icon"   => "mark_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
      "AccessMethod"   => "RegisterStudentMarks",
   ),
   "StudentAbsences" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=StudentAbsences&Student=#ClassStudent",
      "Name"    => "Faltas",
      "Title"     => "Gerenciar Faltas do Aluno - todas as Disciplinas",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
      "AccessMethod"   => "RegisterStudentAbsences",
   ),
   "StudentTotals" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=StudentTotals&Student=#ClassStudent",
      "Name"    => "Totais",
      "Title"     => "Gerenciar Faltas e Avaliações do Aluno - todas as Disciplinas",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Icon"   => "totals_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
      "AccessMethod"   => "RegisterStudentTotals",
   ),
   "StudentPrint" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=StudentTotals&Latex=1&Student=#ClassStudent",
      "Name"    => "Ficha",
      "Title"     => "Ficha do Aluno com Observações",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Icon"   => "totals_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "StudentPrintNoObs" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=StudentTotals&Latex=1&NoObs=1&Student=#ClassStudent",
      "Name"    => "Ficha Simples",
      "Title"     => "Ficha do Aluno sem Observações",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Icon"   => "print_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "History" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Students&Action=History&ID=#ID",
      "Name"    => "Historico",
      "Title"     => "Historico - Vida Escolar do(a) Aluno(a)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "history_light.png",
      "Handler"   => "HandleHistory",
   ),
   "Matriculate" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Students&Action=Matriculate&ID=#ID",
      "Name"    => "Matricular",
      "Title"     => "Matricular Aluno(a)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "schedule_light.png",
      "Handler"   => "HandleMatricula",
      "Singular"   => TRUE,
   ),
   "Remanage" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Students&Action=Remanage&Period=#Period&Class=#Class&ID=#ID",
      "Name"    => "Remanejar",
      "Title"     => "Remanejar Aluno(a)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      //"Icon"   => "schedule_light.png",
      "Handler"   => "HandleRemanage",
      "Singular"   => TRUE,
   ),
   "Remove" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=ClassStudents&Action=Remove&Student=#ID",
      "Name"    => "Deletar",
      "Title"     => "Deletar Aluno(a)",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "delete_light.png",
      "Handler"   => "HandleRemove",
   ),
);
