array
(
   "Dayly" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=Dayly&Class=#Class&Disc=#ID",
      "Name"    => "Diário Eletrônico",
      "Title"     => "Diário Eletrônico da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "schedule_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "Dayly1" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=Dayly&Class=#ID",
      "Name"    => "Diário Eletrônico",
      "Title"     => "Início do Diário Eletrônico da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "schedule_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyPrints" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyPrints&Class=#ID",
      "Name"    => "Imprimíveis",
      "Title"     => "Gerar Impressos",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "print_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyTeacher" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyTeacher&Disc=#ID",
      "Name"    => "Diários Eletrônicos",
      "Title"     => "Diários Eletrônicos",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "schedule_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyCalendar" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyCalendar&Class=#ID",
      "Name"    => " Calendário",
      "Title"     => "Vizualizar o Calendário",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "copy_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyContents" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyContents&Class=#ID",
      "Name"    => "Conteúdos",
      "Title"     => "Cadastrar Conteúdos das Aulas Lançadas",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "copy_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyContentsDates" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyContentsDates&Class=#ID",
      "Name"    => "Lançar Aulas",
      "Title"     => "Lançar Dias de Aula",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "copy_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyContentsPrint" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyContentsPrint&Latex=1&Class=#ID",
      "Name"    => "Versão Imprimível",
      "Title"     => "Gerar Versão Imprimível (PDF) Conteúdos",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "copy_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyStudents" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyStudents&Class=#ID",
      "Name"    => "Alunos e Observações",
      "Title"     => "Alunos e Observações da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "students_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAbsences" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAbsences&Class=#ID",
      "Name"    => "Freqüencias",
      "Title"     => "Gerenciar Freqüencias da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAbsencesPrint" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAbsencesPrint&Latex=1&Class=#ID",
      "Name"    => "Versão Imprimível",
      "Title"     => "Gerar Versão Imprimível (PDF), Freqüencias",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAbsencesStats" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAbsencesStats&Class=#ID",
      "Name"    => "Resumo",
      "Title"     => "Freqüencias da Disciplina, Resumo",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAbsencesMonths" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAbsencesMonths&Class=#ID",
      "Name"    => "Resumo por Mês",
      "Title"     => "Freqüencias da Disciplina, Resumo por Mês",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAbsencesSemesters" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAbsencesSemesters&Class=#ID",
      "Name"    => "Resumo por Trimestre",
      "Title"     => "Freqüencias da Disciplina, Resumo por Trimestre",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "absences_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyAssessments" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyAssessments&Class=#ID",
      "Name"    => "Avaliações",
      "Title"     => "Gerenciar Avaliações da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "mark_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyMarks" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyMarks&Class=#ID",
      "Name"    => "Notas",
      "Title"     => "Gerenciar Notas da Disciplina",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "mark_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
   "DaylyMarksPrint" => array
   (
      "Href"     => "",
      "HrefArgs" => "ModuleName=Classes&Action=DaylyMarksPrint&Latex=1&Class=#ID",
      "Name"    => "Versão Imprimível",
      "Title"     => "Gerar Versão Imprimível (PDF) de Notas",
      "Public"   => 0,
      "Person"   => 0,
      "Admin"   => 0,
      "Handler"   => "",
      "Icon"   => "mark_light.png",
      "Handler"   => "HandleClass",
      //"Target"   => "_Classes",
      "Singular"   => TRUE,
   ),
 );
