array
(
   "Basic" => array
   (
      "Name" => "Basicos",
      "Data" => array("Name","Title","Department"),
      "Admin" => 1,
      "Person" => 0,
      "Public" => 1,
      "Secretary" => 1,
      "Coordinator" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Clerk" => 1,
      "Teacher"     => 1,
      "Single"     => FALSE,
    ),
   "Address" => array
   (
      "Name" => "Endereços",
      "Data" => array("Address","Area","City","State","ZIP"),
      "Admin" => 1,
      "Person" => 0,
      "Public" => 1,
      "Secretary" => 1,
      "Coordinator" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Clerk" => 1,
      "Teacher"     => 1,
    ),
   "Contacts" => array
   (
      "Name" => "Contatos",
      "Data" => array("WWW","Email","Address","Phone","Fax"),
      "Admin" => 1,
      "Person" => 0,
      "Public" => 1,
      "Secretary" => 1,
      "Coordinator" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Clerk" => 1,
      "Teacher"     => 1,
   ),
   "Mail" => array
   (
      "Name" => "Emails do Sistema",
      "Data" => array("AdmEmail","AdmEmailPassword","CCEmail","FromName"),
      "Admin" => 1,
      "Person" => 0,
      "Teacher" => 0,
      "Coordinator" => 1,
      "Distributor" => 0,
      "Public" => 0,
      "Coordinator" => 1,
      "Secretary" => 1,
      "Medical" => 0,
      "Nurse" => 0,
      "Clerk" => 0,
      "Teacher"     => 0,
    ),
);
