array
(
   "ID" => array
   (
      "Name" => "ID",
      "Sql" => "INT NOT NULL PRIMARY KEY AUTO_INCREMENT",
      "Search" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 1,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Department" => array
   (
      "Name" => "Secretaria",
      "Sql" => "INT",
      "SqlClass" => "Departments",
      "Search" => TRUE,
      "Compulsory" => FALSE,
      "SqlWhere" => "ID=#Department",
      "NoSearchEmpty" => TRUE,
      "GETSearchVarName" => "Department",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Protocol" => array
   (
      "Name" => "Protocolo",
      "Sql" => "INT",
      "SqlClass" => "Protocols",
      "Search" => TRUE,
      "Compulsory" => FALSE,
      "GETSearchVarName" => "Protocol",
      "SqlWhere" => "Department=#Department",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Place" => array
   (
      "Name" => "Local",
      "Sql" => "INT",
      "SqlClass" => "Places",
      "Search" => TRUE,
      "Compulsory" => FALSE,
      "GETSearchVarName" => "Place",
      "SqlWhere" => "Department=#Department",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 2,
      "Nurse" => 2,
      "Receptionist" => 1,
   ),
   "Target" => array
   (
      "Name" => "Consultado",
      "Sql" => "INT",
      "SqlClass" => "People",
      "Search" => TRUE,
      //"NoSearchEmpty" => TRUE,
      "Compulsory" => FALSE,
      "SearchFieldMethod" => "MakeTargetSelect",
      "GETSearchVarName" => "Target",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 2,
      "Receptionist" => 2,
   ),
   "Owner" => array
   (
      "Name" => "Lançado por",
      "Sql" => "INT",
      "SqlClass" => "People",
      "Search" => TRUE,
      //"NoSearchEmpty" => TRUE,
      "Compulsory" => FALSE,
      //"SearchFieldMethod" => "MakeTargetSelect",
      //"GETSearchVarName" => "Target",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Person" => array
   (
      "Name" => "Interessado",
      "Sql" => "INT",
      "SqlClass" => "People",
      "Search" => TRUE,
      "Compulsory" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 2,
      "Nurse" => 2,
      "Receptionist" => 2,
   ),
   "Date" => array
   (
      "Name" => "Data",
      "Size" => "10",
      "Sql" => "INT",
      "Search" => TRUE,
      "Compulsory" => FALSE,
      "IsDate" => TRUE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Hour" => array
   (
      "Name" => "Horário",
      "Size" => "5",
      "Sql" => "CHAR(5)",
      "Search" => FALSE,
      "Compulsory" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Status" => array
   (
      "Name" => "Status",
      "Sql" => "ENUM",
      "Search" => TRUE,
      "SearchDefault" => 1,
      //"SearchCheckBox"     => TRUE,
      "Compulsory" => FALSE,
      "Values" => array("Aberta","Fechada"),
      "TriggerFunction" => "ChangeStatus",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 2,
      "Medical" => 2,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "StatusDate" => array
   (
      "Name" => "Status Alterada, Data",
      "Title" => "Status Alterada através Digitação de Senha",
      "Sql" => "INT",
      "Search" => TRUE,
      "Compulsory" => FALSE,
      "TimeType" => 1,
      "Default" => " 0",

      "Public" => 0,
      "Person" => 0,
      "Admin" => 1,
      "Secretary" => 1,
      "Medical" => 1,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Name" => array
   (
      "Name" => "Descrição",
      "Title" => "Digite Descrição Breve",
      "Size" => "50",
      "Sql" => "VARCHAR(255)",
      "SqlWhere" => "",
      "Search" => TRUE,
      "Compulsory" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 2,
      "Medical" => 2,
      "Nurse" => 2,
      "Receptionist" => 2,
   ),
   "Resume" => array
   (
      "Name" => "Resumo",
      "Title" => "Digite Resumo",
      "Size" => "50x20",
      "Sql" => "TEXT",
      "Search" => FALSE,
      "Compulsory" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 2,
      "Medical" => 2,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
   "Conclusion" => array
   (
      "Name" => "Conclusão",
      "Title" => "Digite Conclusão",
      "Size" => "50",
      "Sql" => "TEXT",
      "Search" => FALSE,
      "Compulsory" => FALSE,

      "Public" => 0,
      "Person" => 0,
      "Admin" => 2,
      "Secretary" => 2,
      "Medical" => 2,
      "Nurse" => 1,
      "Receptionist" => 1,
   ),
);