array
(
      "00_Personal" => array
      (
         'Title' => 'Pessoal:',

         'Public' => 1,
         'Person' => 1,
         'Secretary' => 1,
         'Coordinator' => 1,
         'Medical' => 1,
         'Nurse' => 1,
         'Receptionist' => 1,
         'Admin' => 1,
         '00_Top' => array
         (
            'Name' => 'Início',
            'Title' => 'Voltar ao Início',
            'Href' => '?Unit=#Unit&Action=Start',

            'Public' => 1,
            'Person' => 1,
            'Secretary' => 1,
            'Coordinator' => 1,
            'Medical' => 1,
            'Nurse' => 1,
            'Receptionist' => 1,
            'Admin' => 1,
         ),
         '10_Logon' => array
         (
            'Name' => 'Logon',
            'Href' => '?Unit=#Unit&Action=Logon',
            'Public' => 1,
            'Person' => 0,
            'Secretary' => 0,
            'Coordinator' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin' => 0,
          ),
         '20_Recover' => array
         (
            'Name' => 'Recuperar Senha',
            'Href' => '?Unit=#Unit&Action=Recover',
            'Public' => 0,
            'Person' => 0,
            'Coordinator' => 0,
            'Secretary' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin' => 0,
          ),
         '30_Logoff' => array
         (
            'Name' => 'Logoff',
            'Title' => 'Efetuar Logoff do Sistema',
            'Href' => '?Unit=#Unit&Action=Logoff',
            "SiPE" => 1,
            "SiDS" => 0,
            'Public'      => 0,
            'Person'      => 1,
            'Secretary'     => 0,
            'Coordinator' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin'       => 1,
         ),
         '40_NewPassword' => array
         (
            'Name' => 'Alterar Senha',
            'Title' => 'Alterar minha Senha',
            'Href' => '?Unit=#Unit&Action=NewPassword',
            'Public'      => 0,
            'Person'      => 0,
            'Secretary'     => 1,
            'Coordinator' => 1,
            'Clerk'     => 1,
            'Medical' => 1,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin'       => 1,
         ),
         '50_SU' => array
         (
            'Name' => 'Trocar Usuário',
            'Title' => 'Virar para outro Usuário',
            'Href' => '?Unit=#Unit&Action=SU',
            'Public'      => 0,
            'Person'      => 0,
            'Secretary'     => 0,
            'Coordinator' => 1,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin'       => 1,
         ),
         '60_MyData' => array
         (
            'Name' => 'Meus Dados',
            'Title' => 'Editar meus Dados Pessoais',
            'Href' => '?Unit=#Unit&ModuleName=People&Action=Edit&ID=#LoginID',
            'Public'      => 0,
            'Person'      => 0,
            'Secretary'     => 1,
            'Coordinator' => 1,
            'Clerk'     => 1,
            'Teacher'     => 1,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin'       => 1,
         ),
         '70_MyUnit' => array
         (
            'Name' => 'Minha Unidade',
            'Title' => 'Editar Dados da Minha Unidade',
            'Href' => '?Unit=#Unit&Action=MyUnit',
            'Public'      => 0,
            'Person'      => 0,
            'Coordinator' => 0,
            'Secretary'     => 0,
            'Clerk'     => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Receptionist' => 0,
            'Admin'       => 0,
         ),
      ),
      "01_Profile" => array
      (
         'Title' => 'Perfís:',
         "Method" => "HtmlProfilesMenu",

         'Public' => 0,
         'Person' => 1,
         'Secretary' => 1,
         'Medical' => 1,
         'Nurse' => 1,
         'Admin' => 1,
         'Receptionist' => 1,
         'Coordinator' => 1,
      ),
      "02_Actions" => array
      (
         'Title' => 'Dados Gerais:',

         'Public' => 0,
         'Person' => 1,
         'Secretary' => 1,
         'Coordinator' => 1,
         'Medical' => 0,
         'Nurse' => 0,
         'Admin' => 1,
         'Receptionist' => 1,
         'Clerk' => 1,
         'Teacher' => 1,
         '00_Log' => array
         (
            'Name' => 'Logs',
            'Title' => 'Pesquisar Logs',
            'Href' => '?Unit=#Unit&ModuleName=Logs&Action=Search',

            'Public' => 0,
            'Person' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Admin' => 1,
            'Receptionist' => 0,
            'Secretary' => 1,
            'Coordinator' => 0,
            'Clerk' => 0,
            'Teacher' => 0,
         ),
         '01_Grade' => array
         (
            'Name' => 'Grades',
            //'Title' => 'Gerenciar Grades',
            'Href' => '?Unit=#Unit&ModuleName=Grade&Action=Search',

            'Public' => 0,
            'Person' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Admin' => 1,
            'Receptionist' => 0,
            'Secretary' => 1,
            'Coordinator' => 1,
            'Clerk' => 1,
            'Teacher' => 1,
         ),
         '02_Periods' => array
         (
            'Name' => 'Períodos',
            //'Title' => 'Períodos',
            'Href' => '?Unit=#Unit&ModuleName=Periods&Action=Search',

            'Public' => 0,
            'Person' => 0,
            'Medical' => 0,
            'Nurse' => 0,
            'Admin' => 1,
            'Receptionist' => 0,
            'Coordinator' => 1,
            'Secretary' => 1,
            'Clerk' => 1,
            'Teacher' => 1,
         ),
         '03_Dates' => array
         (
            'Name' => 'Datas',
            'Title' => 'Gerenciar Datas',
            'Href' => '?Unit=#Unit&ModuleName=Dates&Action=Search',

            'Public' => 0,
            'Person' => 0,
            'Admin' => 1,
            'Secretary' => 0,
            'Coordinator' => 0,
            'Clerk' => 0,
            'Teacher' => 0,
         ),
         '04_Schools' => array
         (
            'Name' => 'Escolas',
            'Href' => '?Unit=#Unit&School=#School&ModuleName=Schools&Action=Search',

            'Public' => 0,
            'Person' => 0,
            'Secretary' => 1,
            'Medical' => 0,
            'Nurse' => 0,
            'Admin' => 1,
            'Receptionist' => 0,
            'Coordinator' => 1,
            'Clerk' => 1,
            'Teacher' => 1,
         ),
         "05_Teachers" => array
         (
            "Name" => "Professores",
            //"Title" => "Usuários dos Sistema",
            'Href' => '?Unit=#Unit&ModuleName=Users&Action=Search',
            'Public' => 0,
            'Person' => 0,
            'Secretary' => 0,
            'Coordinator' => 1,
            'Admin'     => 0,
            'Clerk'     => 1,
            'Teacher'    => 0,
         ),
         "05_Users" => array
         (
            "Name" => "Usuários",
            //"Title" => "Usuários dos Sistema",
            'Href' => '?Unit=#Unit&ModuleName=Users&Action=Search',
            'Public' => 0,
            'Person' => 0,
            'Secretary' => 1,
            'Coordinator' => 0,
            'Admin'     => 1,
            'Clerk'     => 0,
            'Teacher'    => 0,
         ),
         "06_Clerks" => array
         (
            "Name" => "Acesso aos Escolas",
            "Title" => "Permissões de Acesso, Sec. Escolares",
            'Href' => '?Unit=#Unit&ModuleName=Clerks&Action=Search&Clerks=1',
            'Public' => 0,
            'Person' => 0,
            'Secretary' => 1,
            'Coordinator' => 1,
            'Admin'     => 1,
            'Clerk'     => 0,
            'Teacher'    => 0,
         ),
      ),
      "02_Schools" => array
      (
         'Title' => 'Escolas:',
         "Method" => "SchoolsMenu",

         'Public' => 0,
         'Person' => 0,
         'Secretary' => 1,
         'Medical' => 0,
         'Clerk' => 1,
         'Teacher' => 1,
         'Nurse' => 0,
         'Admin' => 1,
         'Receptionist' => 0,
         'Coordinator' => 1,
      ),
);
