array
(
      "HeadTable" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Schools&Action=&HeadTable&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Cabeçalhos dos Impressos",
        "Title"     => "Cabeçalhos dos Impressos",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "HandleHeadTableForm",
        "Icon"   => "time_light.png",
        "Singular"   => TRUE,
     ),
      "Periods" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Schools&Action=&Periods&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Periodos",
        "Title"     => "Periodos da Escola",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "HandlePeriods",
        "Icon"   => "time_light.png",
        "Singular"   => TRUE,
     ),
      "Clerks" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Schools&Action=Clerks&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Secretários",
        "Title"     => "Secretários de #Name",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "HandleClerks",
        "Icon"   => "people_light.png",
        //"Target"   => "_People",
        "Singular"   => TRUE,
     ),
      "Teachers" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Users&Action=Search&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Professores",
        "Title"     => "Professores de #Name",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "",
        "Icon"   => "teacher_light.png",
        //"Target"   => "_People",
     ),
      "Students" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Students&Action=Search&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Alunos",
        "Title"     => "Alunos de #Name",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "",
        "Icon"   => "people_light.png",
        //"Target"   => "_Students",
     ),
      "Classes" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Classes&Action=Search&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Turmas",
        "Title"     => "Turmas de #Name",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 1,
        "Secretary"   => 1,
        "Handler"   => "",
        "Icon"   => "students_light.png",
        //"Target"   => "_Students",
     ),
      "Import" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Classes&Action=Import&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Importar",
        "Title"     => "Importar Turmas",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Clerk"   => 0,
        "Teacher"   => 0,
        "Secretary"   => 0,
        "Handler"   => "",
        "Icon"   => "add_light.png",
        //"Target"   => "_Students",
     ),
      "HtmlTitles" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Schools&Action=HtmlTitles&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Layout das Telas",
        "Title"     => "Titulos e Icones nas Telas do Sistema",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Secretary"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 0,
        "Handler"   => "HandleHtmlTitles",
        "Singular"   => TRUE,
        //"Target"   => "_Students",
      ),
      "LatexTitles" => array
      (
        "Href"     => "",
        "HrefArgs" => "ModuleName=Schools&Action=LatexTitles&School=".$this->ApplicationObj->GetSchoolID(),
        "Name"    => "Layout dos Impressos",
        "Title"     => "Titulos e Icones nas Telas em Impressos",
        "Public"   => 0,
        "Person"   => 0,
        "Admin"   => 1,
        "Secretary"   => 1,
        "Clerk"   => 1,
        "Teacher"   => 0,
        "Handler"   => "HandleLatexTitles",
        "Singular"   => TRUE,
        //"Target"   => "_Students",
     ),
 );
